### ISSUE TITLE
Micetigri Api for getting image of mice is down..

### ISSUE THREAD

**Issue by NekoTony** [fewfre/TransformiceDressroom#4] opened 2017-09-22 11:04 UTC

**Comment by NekoTony** [comment] 2017-09-22 11:08
Will you be able to provide an alternate way that converts dress_code data from https://club-mice.com/api/api.php?user=NekoTonyy and return that as an image?

**Comment by toreyjs** [comment] 2017-09-22 18:35
How long has it been down / has the site owner been contacted and made any reply? I don't plan on re-inventing the wheel if I don't have to. This also seems like a massive pain to do (since I can't test any script I make this since I use a shared host that can't run a swf on the server). Plus just having it spit back the image is likely a bad idea, so it would need to be paired with some kinda thumbnailer / cache / db (which I have 0 interest in doing).

If the Micetigri version has been down for a few weeks I'll look into it (though no promises). And someone else would have to handle the hosting / image serving part (thumbnailer / cache / etc).

**Comment by fewfre** [comment] 2017-09-22 19:17
How long has it been down / has the site owner been contacted and made any reply? I don't plan on re-inventing the wheel if I don't have to. This also seems like a pain to do (since I can't test any script I make this since I use a shared host that can't run a swf on the server). Plus just having it spit back the image is likely a bad idea, so it would need to be paired with some kinda thumbnailer / cache / db (which I have 0 interest in doing).

If the Micetigri version has been down for a few weeks I'll look into it. And someone else would have to handle the hosting / image serving part (thumbnailer / cache / etc) since my server would likely have issues handling it.

**Comment by fewfre** [comment] 2017-09-23 14:50
It looks like it's possible in php to get an image from a swf using something like [https://github.com/alchemy-fr/PHPSwftools]this(url), but it does require something to be installed on the server. Plus I couldn't really find anything that would wait for the swf to load dependencies (this only seems to extract content from the main swf without waiting for it to load resources), which doesn't allow me to get assets needed. "SWFTools" also seems to have not been updated for a few years; it could be it starting to run into issues which is why the Micetigri version stopped working (or may be unrelated / might be using a different version).

Hitting the "Contact us" form on Micetigri, it looks like [http://atelier801.com/profile?pr=Thewav]Thewav(url) is the person to address with problems on the site. I think it would be best to contact them and see if they / the original dev can fix the problem (since they have most of the work done, and should be familiar with it). If they don't respond or come back saying they won't fix (not can't, just won't) then I'll maybe try looking into it more.

**Comment by NekoTony** [comment] 2017-09-25 00:28
I'm using python and i'll try contacting the person

**Comment by NekoTony** [comment] 2017-10-02 17:16
Literally no response, i could host it.

**Comment by fewfre** [comment] 2017-10-15 19:05
Hello, sorry for delayed response. I've looked into it a bit more and tried a few things, but I still can't figure out how to make something that takes an image of a swf to wait for asset loading to finish. Most tools either seems to take a snapshot as soon as it starts or only extracts a specific movieclip/sprite.

I have a couple more ideas on how to maybe tackle the issue, but I don't have time to address them right now and it might be awhile before I do. Sorry for the delay. If someone else wants to look into it, they're free to modify the dressroom code as needed / create a pull request.

**Comment by NekoTony** [comment] 2017-11-01 14:51
Sorry for the lat reply, as well. Been busy with school. 

You made it possible to upload it to imgur so you must have come up with some temporary solution to host the file until it uploads to imgur. I've done the same w/ my profile decorations project, only saving it for a short while.

The only problem i see is gathering the mouse outfit data by username and applying it to the swf.

**Comment by fewfre** [comment] 2017-11-01 23:46
Imgur just lets you upload the image data directly, so no need to save. But saving isn't the issue anyways. The issue is running the swf as a script on the server. swfs are meant to be used on the front end, so running them as a server script is clunky, especially since it has to first load in other asset swfs first. If nothing else I'm not sure how the swf would tell you it's "done".

As I said I have a couple more ideas how to address it (and have a super hacky method that could work if all else fails, using cURL) but don't have the time to address this currently. I've also had issues with my Flash Professional installation after deleting some stuff, so I can't update anything until that's fixed.

applying the outfit data would be the easy part due to the club-mice api; I would just expose the current url params to the command line / add a save name. the outfit data would just need to be passed in as the right syntax.

**Closed as completed** 2017-11-21 02:49 UTC
